apiVersion: apps/v1
kind: Deployment
metadata:
  name: finansu-view-deployment
  namespace: finansu
spec:
  selector:
    matchLabels:
      app: finansu-view
  replicas: 1
  template:
    metadata:
      labels:
        app: finansu-view
    spec:
      containers:
        - name: finansu-view-container
          image: nutfes/finansu-view:latest
          resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: finansu-view-service
  namespace: finansu
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: finansu-view
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finansu-view-ingress
  namespace: finansu
  labels:
    name: finansu-view-ingress
spec:
  rules:
  - host: finansu.nutfes.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: finansu-view-service
            port: 
              number: 3000

